name: shotwell
adopt-info: shotwell
grade: stable
confinement: strict
base: core24

slots:
  # for GtkApplication registration
  shotwell:
    interface: dbus
    bus: session
    name: org.gnome.Shotwell

apps:
  shotwell:
    command: usr/bin/shotwell
    extensions: [gnome]
    desktop: usr/share/applications/org.gnome.Shotwell.desktop
    environment:
      HOME: $SNAP_USER_COMMON
    plugs:
      - audio-playback
      - home
      - raw-usb
      - mount-observe
      - hardware-observe
      - removable-media

parts:
  shotwell:
# ext:updatesnap
#   version-format:
#     format: "shotwell-%M.%m.%R"
    plugin: meson
    source: https://gitlab.gnome.org/GNOME/shotwell.git
    source-tag: shotwell-0.32.10
    source-depth: 1
    meson-parameters:
      - --prefix=/usr
      - -Dunity_support=true
    build-environment:
      - LD_LIBRARY_PATH: "${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}\
                          /snap/gnome-46-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libunity"
    parse-info: [usr/share/metainfo/org.gnome.Shotwell.appdata.xml]
    build-packages:
      - cmake
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgphoto2-dev
      - libgexiv2-dev
      - libraw-dev
      - libmtp-dev
    stage-packages:
      - libexif12
      - libgcr-ui-3-1
      - libgdata22
      - libgexiv2-2
      - libgphoto2-6t64
      - libgphoto2-port12t64
      - libraw23t64
      - libmtp9t64

  cleanup:
    after: [shotwell]
    plugin: nil
    build-snaps: [core24, gtk-common-themes]
    override-prime: |
      set -eux
      for snap in "core24" "gtk-common-themes"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* \
          -exec rm -f "$CRAFT_PRIME/{}" \;
      done
      for snap in "core24"; do
        cd "/snap/$snap/current/usr/lib"
        for filename in [ *.so* ]; do
          rm -f "$CRAFT_PRIME/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/$filename"
        done
        cd "/snap/$snap/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR"
        for filename in [ *.so* ]; do
          rm -f "$CRAFT_PRIME/usr/lib/$filename"
        done
      done
